In [9]:
import pandas as pd
import numpy as np

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix # model 평가

In [28]:
from sklearn.model_selection import LeaveOneOut, cross_val_score, KFold

In [12]:
y = pd.read_csv('../dataset/label.csv')
y = y['label']
y

0      0
1      1
2      1
3      0
4      1
      ..
137    0
138    1
139    0
140    1
141    0
Name: label, Length: 142, dtype: int64

In [13]:
orginal_df = pd.read_csv('../dataset/oasis_longitudinal.csv')

# imputation data
GRAPE_imputate = pd.read_csv('../dataset/GRAPE_imputate.csv').iloc[:,1:]
mice_imputate = pd.read_csv('../dataset/mice_imputate.csv').iloc[:,1:]
mean_imputate = pd.read_csv('../dataset/mean_imputate.csv').iloc[:,1:]


# GRAPE

In [14]:
# train test split
grape_train_X, grape_test_X, train_y, test_y = train_test_split(GRAPE_imputate, y, stratify=y, test_size = 0.3, random_state= 123)

print(f'grape_train_X Shape : {grape_train_X.shape}')
print(f'grape_test_X Shape : {grape_test_X.shape}')
print(f'train_y Shape : {train_y.shape}')
print(f'test_y Shape : {test_y.shape}')

grape_train_X Shape : (99, 9)
grape_test_X Shape : (43, 9)
train_y Shape : (99,)
test_y Shape : (43,)


In [15]:
# 모델 학습
model_grape = LogisticRegression(random_state=0)
model_grape.fit(grape_train_X, train_y)

LogisticRegression(random_state=0)

In [27]:
# 평가
print("훈련 세트 정확도: {:.5f}".format(model_grape.score(grape_train_X, train_y )) )
print("테스트 세트 정확도: {:.5f}".format(model_grape.score(grape_test_X, test_y)) )

훈련 세트 정확도: 0.83838
테스트 세트 정확도: 0.83721


# MICE

In [20]:
# train test split
mice_train_X, mice_test_X, train_y, test_y = train_test_split(mice_imputate, y, stratify=y, test_size = 0.3, random_state= 123)

print(f'mice_train_X Shape : {mice_train_X.shape}')
print(f'mice_test_X Shape : {mice_test_X.shape}')
print(f'train_y Shape : {train_y.shape}')
print(f'test_y Shape : {test_y.shape}')

mice_train_X Shape : (99, 9)
mice_test_X Shape : (43, 9)
train_y Shape : (99,)
test_y Shape : (43,)


In [21]:
# 모델 학습
model_mice = LogisticRegression(random_state=0)
model_mice.fit(mice_train_X, train_y)

LogisticRegression(random_state=0)

In [22]:
# 평가
print("훈련 세트 정확도: {:.5f}".format(model_mice.score(mice_train_X, train_y )) )
print("테스트 세트 정확도: {:.5f}".format(model_mice.score(mice_test_X, test_y)) )

훈련 세트 정확도: 0.859
테스트 세트 정확도: 0.767


# MEAN

In [23]:
# train test split
mean_train_X, mean_test_X, train_y, test_y = train_test_split(mean_imputate, y, stratify=y, test_size = 0.3, random_state= 123)

print(f'mean_train_X Shape : {mean_train_X.shape}')
print(f'mean_test_X Shape : {mean_test_X.shape}')
print(f'train_y Shape : {train_y.shape}')
print(f'test_y Shape : {test_y.shape}')

mean_train_X Shape : (99, 9)
mean_test_X Shape : (43, 9)
train_y Shape : (99,)
test_y Shape : (43,)


In [24]:
# 모델 학습
model_mean = LogisticRegression(random_state=0)
model_mean.fit(mean_train_X, train_y)

LogisticRegression(random_state=0)

In [26]:
# 평가
print("훈련 세트 정확도: {:.5f}".format(model_mean.score(mean_train_X, train_y )) )
print("테스트 세트 정확도: {:.5f}".format(model_mean.score(mean_test_X, test_y)) )

훈련 세트 정확도: 0.85859
테스트 세트 정확도: 0.83721


# Using LeaveOneOut CV

In [29]:
# create object
model_grape = LogisticRegression(random_state=0)
model_mice = LogisticRegression(random_state=0)
model_mean = LogisticRegression(random_state=0)

# LeaveOneOut model
loo = LeaveOneOut() 

# test validation
# LOOCV
grape_loo_score = cross_val_score(model_grape, GRAPE_imputate, y, cv=loo)
mice_loo_score = cross_val_score(model_mice, mice_imputate, y, cv=loo) 
mean_loo_score = cross_val_score(model_mean, mean_imputate, y, cv=loo) 

In [33]:
# cv result
print('grape score_loocv \n{:.5f}'.format(grape_loo_score.mean()))
print('mice score_loocv \n{:.5f}'.format(mice_loo_score.mean()))
print('mean score_loocv \n{:.5f}'.format(mean_loo_score.mean()))

grape score_loocv 
0.82394
mice score_loocv 
0.83099
mean score_loocv 
0.83803


In [30]:
grape_loo_score

array([1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1.])

In [31]:
mice_loo_score

array([1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1.])

In [32]:
mean_loo_score

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1.])