In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [3]:
from sklearn.metrics import accuracy_score, confusion_matrix # model 평가

In [4]:
from sklearn.model_selection import LeaveOneOut, cross_val_score, KFold

In [5]:
y = pd.read_csv('../dataset/label.csv')
y = y['label']
y

0      0
1      1
2      1
3      0
4      1
      ..
137    0
138    1
139    0
140    1
141    0
Name: label, Length: 142, dtype: int64

In [6]:
orginal_df = pd.read_csv('../dataset/original_data.csv')

# imputation data
GRAPE_imputate = pd.read_csv('../dataset/GRAPE_imputate.csv').iloc[:,1:]
mice_imputate = pd.read_csv('../dataset/mice_imputate.csv').iloc[:,1:]
mean_imputate = pd.read_csv('../dataset/mean_imputate.csv').iloc[:,1:]

# Original

In [7]:
# train test split
org_train_X, org_test_X, train_y, test_y = train_test_split(orginal_df, y, stratify=y, test_size = 0.3, random_state= 123)

print(f'org_train_X Shape : {org_train_X.shape}')

print(f'org_test_X Shape : {org_test_X.shape}')
print(f'train_y Shape : {train_y.shape}')
print(f'test_y Shape : {test_y.shape}')

org_train_X Shape : (99, 10)
org_test_X Shape : (43, 10)
train_y Shape : (99,)
test_y Shape : (43,)


In [8]:
# 모델 학습
model_org = SVC(kernel = 'linear')
model_org.fit(org_train_X, train_y)

SVC(kernel='linear')

In [9]:
# 평가
print("훈련 세트 정확도: {:.5f}".format(model_org.score(org_train_X, train_y )) )
print("테스트 세트 정확도: {:.5f}".format(model_org.score(org_test_X, test_y)) )

훈련 세트 정확도: 1.00000
테스트 세트 정확도: 1.00000


# GRAPE

In [10]:
# train test split
grape_train_X, grape_test_X, train_y, test_y = train_test_split(GRAPE_imputate, y, stratify=y, test_size = 0.3, random_state= 123)

print(f'grape_train_X Shape : {grape_train_X.shape}')
print(f'grape_test_X Shape : {grape_test_X.shape}')
print(f'train_y Shape : {train_y.shape}')
print(f'test_y Shape : {test_y.shape}')

grape_train_X Shape : (99, 9)
grape_test_X Shape : (43, 9)
train_y Shape : (99,)
test_y Shape : (43,)


In [11]:
# 모델 학습
model_grape = SVC(kernel = 'linear')
model_grape.fit(grape_train_X, train_y)

SVC(kernel='linear')

In [12]:
# 평가
print("훈련 세트 정확도: {:.5f}".format(model_grape.score(grape_train_X, train_y )) )
print("테스트 세트 정확도: {:.5f}".format(model_grape.score(grape_test_X, test_y)) )

훈련 세트 정확도: 0.85859
테스트 세트 정확도: 0.83721


# MICE

In [13]:
# train test split
mice_train_X, mice_test_X, train_y, test_y = train_test_split(mice_imputate, y, stratify=y, test_size = 0.3, random_state= 123)

print(f'mice_train_X Shape : {mice_train_X.shape}')
print(f'mice_test_X Shape : {mice_test_X.shape}')
print(f'train_y Shape : {train_y.shape}')
print(f'test_y Shape : {test_y.shape}')

mice_train_X Shape : (99, 9)
mice_test_X Shape : (43, 9)
train_y Shape : (99,)
test_y Shape : (43,)


In [14]:
# 모델 학습
model_mice = SVC(kernel = 'linear')
model_mice.fit(mice_train_X, train_y)

SVC(kernel='linear')

In [15]:
# 평가
print("훈련 세트 정확도: {:.5f}".format(model_mice.score(mice_train_X, train_y )) )
print("테스트 세트 정확도: {:.5f}".format(model_mice.score(mice_test_X, test_y)) )

훈련 세트 정확도: 0.84848
테스트 세트 정확도: 0.76744


# MEAN

In [16]:
# train test split
mean_train_X, mean_test_X, train_y, test_y = train_test_split(mean_imputate, y, stratify=y, test_size = 0.3, random_state= 123)

print(f'mean_train_X Shape : {mean_train_X.shape}')
print(f'mean_test_X Shape : {mean_test_X.shape}')
print(f'train_y Shape : {train_y.shape}')
print(f'test_y Shape : {test_y.shape}')

mean_train_X Shape : (99, 9)
mean_test_X Shape : (43, 9)
train_y Shape : (99,)
test_y Shape : (43,)


In [17]:
# 모델 학습
model_mean = SVC(kernel = 'linear')
model_mean.fit(mean_train_X, train_y)

SVC(kernel='linear')

In [18]:
# 평가
print("훈련 세트 정확도: {:.5f}".format(model_mean.score(mean_train_X, train_y )) )
print("테스트 세트 정확도: {:.5f}".format(model_mean.score(mean_test_X, test_y)) )

훈련 세트 정확도: 0.85859
테스트 세트 정확도: 0.83721


# Using LeaveOneOut CV

## linear SVC

In [19]:
# create object
model_org = SVC(kernel = 'linear')
model_grape = SVC(kernel = 'linear')
model_mice = SVC(kernel = 'linear')
model_mean = SVC(kernel = 'linear')

# LeaveOneOut model
loo = LeaveOneOut() 

# test validation
# LOOCV
org_loo_score = cross_val_score(model_org, orginal_df, y, cv=loo)
grape_loo_score = cross_val_score(model_grape, GRAPE_imputate, y, cv=loo)
mice_loo_score = cross_val_score(model_mice, mice_imputate, y, cv=loo) 
mean_loo_score = cross_val_score(model_mean, mean_imputate, y, cv=loo) 

In [20]:
# cv result
print('org score_loocv \n{:.5f}'.format(org_loo_score.mean()))

print('grape score_loocv \n{:.5f}'.format(grape_loo_score.mean()))
print('mice score_loocv \n{:.5f}'.format(mice_loo_score.mean()))
print('mean score_loocv \n{:.5f}'.format(mean_loo_score.mean()))

org score_loocv 
0.99296
grape score_loocv 
0.88028
mice score_loocv 
0.82394
mean score_loocv 
0.87324


In [21]:
org_loo_score

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [22]:
grape_loo_score

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1.])

In [23]:
mice_loo_score

array([1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [24]:
mean_loo_score

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

### Kernel SVC

In [25]:
# create object
model_org = SVC(kernel = 'rbf')
model_grape = SVC(kernel = 'rbf')
model_mice = SVC(kernel = 'rbf')
model_mean = SVC(kernel = 'rbf')

# LeaveOneOut model
loo = LeaveOneOut() 

# test validation
# LOOCV
org_loo_score = cross_val_score(model_org, orginal_df, y, cv=loo)

grape_loo_score = cross_val_score(model_grape, GRAPE_imputate, y, cv=loo)
mice_loo_score = cross_val_score(model_mice, mice_imputate, y, cv=loo) 
mean_loo_score = cross_val_score(model_mean, mean_imputate, y, cv=loo) 

In [26]:
# cv result
print('org score_loocv \n{:.5f}'.format(org_loo_score.mean()))

print('grape score_loocv \n{:.5f}'.format(grape_loo_score.mean()))
print('mice score_loocv \n{:.5f}'.format(mice_loo_score.mean()))
print('mean score_loocv \n{:.5f}'.format(mean_loo_score.mean()))

org score_loocv 
0.50704
grape score_loocv 
0.85915
mice score_loocv 
0.81690
mean score_loocv 
0.80986


In [27]:
org_loo_score

array([1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 1., 0., 1.])

In [28]:
grape_loo_score

array([1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1.])

In [29]:
mice_loo_score

array([1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [30]:
mean_loo_score

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])